### ISSUE TITLE
compute-only vs. path computation RPC in OTN tunnel model

### ISSUE THREAD

**Issue by sergiobelotti** [haomianzheng/IETF-ACTN-YANG-Model#10]
Two correlated comments here:
1) it  seems to me there is a misunderstanding of the concept of "compute-only" mode present in te-tunnel. This mode is not provided by RPC in te-tunnel, but a compute-only tunnel is configured as a usual tunnel , with constraints and properties , but is not configured , and client can get information about the related calculated paths by querying the state of the tunnel. No RPC at all is used. 

2) The description  in the related  text (section 3.3) and also Yang code,  are more close to what we have already in "path computation RPC" and so my suggestion would be  to use path computation RPC , augmenting that directly with technology specifc aspect . So an alignment of the proposed RPC in this draft and the current generic path computation RPC has to be provided.

**Comment by italobusi** [comment]
I think comment 1. has been fixed by the new text in section 3.3 of draft-ietf-ccamp-otn-tunnel-model-03
