### ISSUE TITLE
Describe L1CSM YANG Model

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#118]
> Isn't it customary in the section that includes the tree structure to also provide some brief explanation of the branches and important leaf nodes? Or maybe in another section.

_Originally posted by @italobusi in https://github.com/haomianzheng/IETF-ACTN-YANG-Model/issues/117#issuecomment-1305683474_

**Comment by haomianzheng** [comment]
It is proposed to use the following clip to replace the section 3 title before the tree.

**Comment by italobusi** [comment]
Following other I-Ds we can consider the following document structure:

# 3. L1CSM YANG Model Overview

The L1CSM YANG data model describes the layer 1 connectivity services following the convention defined in [MEF_63] which includes the description of User Network Interface (UNI) access characteristics and L1 virtual connection (L1VC) service characteristics:

    +--rw l1-connectivity
      +--rw access
      |  +--rw unis
      |     +--rw uni* [id]
      |        +--rw id                         string
      |        .......................................
      +--rw services
         +--rw service* [service-id]
            +--rw service-id    string
            ..........................................

The UNI access characteristics can be specified using either the definitions in [MEF_63], which are based on the 3-tuple includes protocol, coding and optical-interface, or the definitions in [ietf-layer1-types], which are based on the client signals in [ITU-T_G.709]:

```
    +--rw (uni-access-type)?
       +--:(mef)
       |  +--rw protocol             identityref
       |  +--rw coding               identityref
       |  +--rw optical-interface    identityref
       +--:(itu)
          +--rw client-signal        identityref
```

The L1VC service characteristics are described by references to the two end points of the point-to-point connectivity:

```
    +--rw endpoint-1
    |  +--rw id     string
    |  +--rw uni    -> /l1-connectivity/access/unis/uni/id
    +--rw endpoint-2
       +--rw id     string
       +--rw uni    -> /l1-connectivity/access/unis/uni/id
```

# 4. L1CSM Tree Diagram

<...>

# 5. YANG Model for L1CSM

<...>

**Comment by italobusi** [comment]
Fixed in https://datatracker.ietf.org/doc/html/[draft-ietf-ccamp-l1csm-yang-19](https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-l1csm-yang-19)
