### ISSUE TITLE
Tom Petch IETF LC comments for draft-ietf-ccamp-layer1-types-16

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#145]
> ISO/IEC C99 is in the I-D but not the I-D References
> 
> IEEE Std 754-2008: is in the I-D but the references have -2019; this topic is fraught - it may be that the  older one is wanted here
> 
> ANSI T1.105-1995: is in the I-D but the references have 2001
> 
> p.5 'section Section'
> 
> p.7 several should that might be SHOULD
> 

---

> YANG module
> 
> description
> /Layer 1 types/ Layer 1 YANG types/
> or perhaps
>  A YANG Data Model for Layer 1 Types
> 
> bandwidth scientific notation
> is the canonical form lower case?
> 
> I like to view the Normative References but think that here I cannot because they are subscription only.  This issue came up before but I cannot remember what the conclusion was and things may have moved on since then.
> 
> ANSI I have never been able to access - subscription only I think.
> 
> ITU-T I have had problems with in the past but I now seem to have access (but they could do with lessons from the datatracker about searching = I really do not want 11587 hits for G.709!)
> 
> IEEE I used to be able to access but now struggle - the website has moved and been 'improved'.  The URL in the HTML version of the I-D work but tell me that I do not have access.  802,3 I have previously downloaded and printed but seemingly no more.  Online viewing such a large document I find time consuming.

---

See:
- https://mailarchive.ietf.org/arch/msg/ccamp/NpTZOZugBCpn1Got8gVaQqgnw8o/
- https://mailarchive.ietf.org/arch/msg/ccamp/x8Yc-XLaeFCp20POWlIPQuTfZIk/

**Comment by danielkinguk** [comment]
Addressed.

**Comment by italobusi** [comment]
Comments addressed: https://mailarchive.ietf.org/arch/msg/ccamp/_XUbTnGebQ2GyabCEgQTqVmEHOA/
