### ISSUE TITLE
AD Review of draft-ietf-ccamp-layer1-types-16

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#147]
> The only editorial feedback I have is from idnits:
> 
>   == Unused Reference: 'RFC8294' is defined on line 1992, but no explicit
>      reference was found in the text
> 

---

See: https://mailarchive.ietf.org/arch/msg/ccamp/VKWYPPQvYtxOHYLvo8XszDDsyQQ/

**Comment by danielkinguk** [comment]
Addressed.

**Comment by italobusi** [comment]
Comments addressed: https://mailarchive.ietf.org/arch/msg/ccamp/n6YK6j2nAdXj4YejnnOI_4DzmS8/
