### ISSUE TITLE
John Scudder's Discuss on draft-ietf-ccamp-layer1-types-16

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#150]
> ----------------------------------------------------------------------
> DISCUSS:
> ----------------------------------------------------------------------
> 
> Please don't forget to consider Tom Petch's review,
> https://mailarchive.ietf.org/arch/msg/last-call/akNb8PDxCI5lw-HWx474EcMp1Cg/ In
> particular, Tom points out some references to possibly-outdated external
> specifications.
> 

- [ ] #145 

> ----------------------------------------------------------------------
> COMMENT:
> ----------------------------------------------------------------------
> 
> In section 4.4 you mention OTN LTPs, I assume you're talking about "logical
> termination points". Please consider expanding LTP, I did check in RFC 7062 to
> see if it's defined there; it's not.
> 
> Also, when you produce a new version, please make sure you update the 2022
> dates... unless there's some reason not to?
> 

---

See: https://mailarchive.ietf.org/arch/msg/ccamp/YCPO3rAKKY8XGT4_h5oP6JhtMh0/

**Comment by danielkinguk** [comment]
Addressed.

**Comment by italobusi** [comment]
Comments addressed: https://mailarchive.ietf.org/arch/msg/ccamp/kg7sKuge8PNBOWURo-n1ieuJbws/
