### ISSUE TITLE
Warren Kumari's No Objection

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#154]
> I had originally written this up as a DISCUSS ballot, but am submitting it as
> NoObjection instead because Eric and John are holding DISCUSS on this.
> 
> The title is "A YANG Data Model for Layer 1 Types", and this speaks to a
> specific subset of L1 types -- the title really should be updated to clarify
> this. In addition, there are many acronyms that should be expanded.
> 

---

See: https://mailarchive.ietf.org/arch/msg/ccamp/VWrR7IsDKD0EiDTNPPrZR4y-u0g/

**Comment by danielkinguk** [comment]
Addressed.

**Comment by italobusi** [comment]
Comments addressed: https://mailarchive.ietf.org/arch/msg/ccamp/Lyxt2DGO3VsndkYap58fWXk5kmo/
