### ISSUE TITLE
Martin Duke's No Objection

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#155]
> Please expand acronyms on first use -- it is much more readable if reader's
> don't have to dig up references and only costs a few words. For example: OTN<
> ODU, HO, LSP, LO.
> 
> It would be useful to precisely define what you mean by "Layer 1" networks,
> which I gather is the physical layer. Or is this about optically switched
> networks, specifically? If so, it would be better to name things accordingly. I
> don't know much about this but it appears that any non-optical Layer 1 network
> (if such a thing exists) is not represented in this YANG module.
> 

---

See: https://mailarchive.ietf.org/arch/msg/ccamp/K1dLqm2uEmdHvyG8vN5GXRK662I/

**Comment by danielkinguk** [comment]
Addressed.

**Comment by italobusi** [comment]
Comments addressed: https://mailarchive.ietf.org/arch/msg/ccamp/U6LQxOrAPUrL5kII1InZvY3YRGo/
