### ISSUE TITLE
Genart last call review of draft-ietf-ccamp-otn-topo-yang-17

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#171]
> Major issues: None
> 
> Minor issues: None
> 
> Nits/editorial comments:
>   == Unused Reference: 'I-D.ietf-ccamp-otn-tunnel-model' is defined on line
>      3662, but no explicit reference was found in the text
> 
>   == Unused Reference: 'RFC4203' is defined on line 3684, but no explicit
>      reference was found in the text
> 
>   == Unused Reference: 'RFC7138' is defined on line 3698, but no explicit
>      reference was found in the text
> 

See: https://mailarchive.ietf.org/arch/msg/ccamp/FX6OJdPNrgSPFUWHx4KcCBzYqNg/

**Comment by haomianzheng** [comment]
updated in -18 and email replied at: https://mailarchive.ietf.org/arch/msg/ccamp/60qvjX5gEILYwgLfuzHYmP4-TUA/
