### ISSUE TITLE
Improving OTN Topology Security Considerations

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#187]
> I agree that the nodes defined in RFC 8795 do not need to copied here. However, the nodes that are defined in this draft, and do not exist in RFC 8795 need to have their own Security Considerations. By leaving the section blank for each of writeable/readable/actionable (RPCs) sections, I am not sure what is being implied. At the minimum, the document needs to say for each of the writeable/readable/actionable sections, that the nodes in this document have no security considerations.

---

- [x] Wait for Mahesh reply: https://mailarchive.ietf.org/arch/msg/ccamp/HdSUAc6JB5kzfJwagoYwky-Dh4g/

**Comment by italobusi** [comment]
Initial reply, explaining the issues with listing all the nodes, sent to the list: https://mailarchive.ietf.org/arch/msg/ccamp/867lL-hshOgSHpmZNc7nN_r84Cc/

**Comment by italobusi** [comment]
Proposed text updates: [draft-ietf-ccamp-otn-topo-yang-SECURITY-SECTION.docx](https://github.com/user-attachments/files/17488189/draft-ietf-ccamp-otn-topo-yang-SECURITY-SECTION.docx)

**Comment by danielkinguk** [comment]
Thanks. I worked with Italo on the text and happy with the results.
