### ISSUE TITLE
Multiplexing Format in otn-types

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#20]
To be discussed: 

So we specify the GFP-F and the GMP multiplexing in the same identity or via different identities in otn-types.yang?

Option A: 
  identity ETH-1Gb {
    base client-signal;
    description
      "Client signal type of 1GbE";
  }

Option B: 
  identity ETH-1Gb-GFPF {
    base client-signal;
    description
      "Client signal type of 1GbE with GFP-F";
  }

  identity ETH-1Gb-GMP {
    base client-signal;
    description
      "Client signal type of 1GbE with GMP";
  }

**Comment by italobusi** [comment]
There are two options to setup an EPL service between two 1GE access links:

1. setup a transparent client signal ETH-1Gb over ODU0, using ietf-trans-client-service
2. setup a (non-transparent) Ethernet client signal with port-based classification over ODU0, using ietf-eth-tran-service
3. 

GMP is always used in case 1 and GFP-F is always in case 2

**Comment by italobusi** [comment]
The only open issue would be about client-signals which can use either AMP or BMP (e.g., STM-16)

**Comment by haomianzheng** [comment]
According to the discussion so far, it is proposed to use option A in the layer1-types. Meanwhile another parameters indicating the multiplexing would be added on the client-signal model. 
The new parameter is going to be re-confirmed when updating the client-signal YANG.

**Comment by italobusi** [comment]
Exported to https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/4
