### ISSUE TITLE
Different Protection on Client service/OTN tunnel

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#23]
Protection parameters have been specified in ietf-te.yang, which is used for tunnel protection. 

Discussion is requested for the necessity of protection for client service, i.e., in the module ietf-trans-client-service and ietf-eth-tran-service. Corresponding parameters need to be incorporated if necessary.

**Comment by italobusi** [comment]
Duplicated with #31
