### ISSUE TITLE
State of Client signal Models - ietf-trans-client-service

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#29]
Regarding the Ethernet model, we are having a state branch: 
          +--ro state
             +--ro operational-state?         identityref
             +--ro provisioning-state?        identityref
             +--ro creation-time?             yang:date-and-time
             +--ro last-updated-time?         yang:date-and-time
             +--ro sending-rate-too-high?     uint32
             +--ro sending-rate-too-low?      uint32
             +--ro receiving-rate-too-high?   uint32
             +--ro receiving-rate-too-low?    uint32

Thus information is also required in ietf-trans-client-service, currently we are having operation-state and provisioning-state, it is proposed to add also the creation-time and last-updated-time. Maybe a grouping is helpful, as folllow: 

Old: 
             +--ro operational-state?        identityref
             +--ro provisioning-state?       identityref
New: 
          +--ro state
             +--ro operational-state?         identityref
             +--ro provisioning-state?        identityref
             +--ro creation-time?             yang:date-and-time
             +--ro last-updated-time?         yang:date-and-time

**Comment by italobusi** [comment]
The resolution of this open issue has been embedded in pull request #32

**Comment by italobusi** [comment]
Closed with pull request #30
