### ISSUE TITLE
Resilience Configuration on ietf-eth-tran-service

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#31]
A few placeholder on resilience configuration will be added into the current ietf-eth-tran-service, which will appear in draft-zheng-ccamp-client-signal-yang-04.  Attributes to be configure include the WTR, hold-off-timer, revert/non-revert and so on... 

An open issue would be where to configure the resilience attributes. A few potential places include: 
1. Resilience on the access port: LAG/DRNI/MC-LAG information; 
2. Resilience on the service instance, usually shown on Pseudowire;  
3. Resilience on the L2 tunnel, which is MPLS-TP tunnel; 
4. Resilience on the L1 tunnel, which is OTN/SDH tunnel; 

Currently, item 4 is supported by te-tunnel model. 

In practice, 2 and 3 are usually not implemented together. On the perspective of service protection, feasible configuration would be 1+2+4 or 1+3+4(all optional) . 

Will need to add the resilience information for 1/2/3 in ietf-eth-tran-service.

**Comment by italobusi** [comment]
Exported to: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/8
