### ISSUE TITLE
Add description on the modelling of the OTN label range

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#39]
Add some description on the modelling of the OTN label range (e.g., how the TS range and the TPN range are related to each other

**Comment by sergiobelotti** [comment]
I'm sorry but I do not find the modification

**Comment by haomianzheng** [comment]
This issue is closed by the update in IETF 106, i.e., draft-ietf-ccamp-layer1-types-03.
