### ISSUE TITLE
Consider removing ODUCn from ietf-layer1-types

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#40]
Given the ODUCn is non-switchable, it is proper to differentiate it with ODUk as well.  Including the ODUCn as a type in layer1-type will be misleading. It is proposed to remove/revise the following in the ietf-layer1-types. 

identity ODUCn {
    base odu-type;  
    description
      "ODUCn protocol (beyond 100G)";
  }

The application of ODUCn to support ODUclient signals will be investigated in separate documents.

**Comment by sergiobelotti** [comment]
Where is the file to look at the modification ??

**Comment by haomianzheng** [comment]
This issue is closed by the update in IETF 106, i.e., draft-ietf-ccamp-layer1-types-03.
