### ISSUE TITLE
Prefix in draft-ietf-ccamp-client-signal-yang-01 Misalignment

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#41]
+-------------+---------------------------+----------------------+
     | Prefix      | YANG module               | Reference            |
     +-------------+---------------------------+----------------------+
     | yang        | ietf-yang-types           | [RFC6991]            |
     | te-types    | ietf-te-types          |[ietf-teas-yang-te-types]|
     | rt-types    | ietf-routing-types        | [RFC8294]            |
     | otn-types   | ietf-otn-types     |[ietf-ccamp-otn-tunnel-model]|
     | etht-types  | ietf-eth-tran-types       | This Document        |
     | clntsvc     | ietf-trans-client-service | This Document        |
     | ethtsvc     | ietf-eth-tran-service     | This Document        |
     |clntsvc-types|ietf-trans-client-svc-types| This Document        |
     +-------------+---------------------------+----------------------+

| otn-types   | ietf-otn-types     |[ietf-ccamp-otn-tunnel-model]| should become
| layer1-types | ietf-layer1-types  |[ietf-ccamp-layer1-typesl]|

**Comment by italobusi** [comment]
Exported to https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/3
