### ISSUE TITLE
Demand on multiple entries for configuration on OTN labels, both TPN & TS would be needed. 

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#45]
The tributary port # in bits 3 to 8 indicates the port number of the ODTU13/23 that is being transported in this 2.5G TS; for the case of ODTU23, a flexible assignment of tributary ports to tributary slots is possible, for the case of ODTU13, this assignment is fixed, the tributary port number equals the tributary slot number. ODTU23 tributary ports are numbered 1 to 4.

Refer to Figure 19-16A in G.709. 

The proposed understanding of the mechanism in the model is that e.g. for a client layer  ODU1 LSP on an ODU3 link you will need two entries in the augmentation of label restriction start/end of TE link , one for TPN and another for TS since the assignment is flexible.

  /* Augment label restrictions end of TE link template */
  augment "/nw:networks/tet:te/tet:templates/"
        + "tet:link-template/tet:te-link-attributes/"
        + "tet:label-restrictions/tet:label-restriction/"
        + "tet:label-end/tet:te-label/tet:technology" {
/*
    when "../../../../../../../nw:network-types/tet:te-topology/"
        + "otntopo:otn-topology" {
      description "Augment OTN TE label";
    }
*/
    description "OTN label.";
    case otn {
      uses layer1-types:otn-label-start-end;
    }
  }

**Comment by italobusi** [comment]
Proposed text change for section 4.3:

>    The OTN Label Range represents the values for the TPN and TS that are
>    available for ODUk LSPs to be setup over a given OTN Link.
> 
>    The OTN Label Range is defined by the label-restriction list, defined
>    in [I-D.ietf-teas-yang-te-types], which, for OTN, should be augmented
>    using the otn-label-range-info grouping.
> 
>    Each entry in the label-restriction list represents either the range
>    of the available TPN values or the range of the available TS values:
>    the range-type attribute in the otn-label-range-info grouping defines
>    the type of range for each entry of the list.
> 
>    Each entry of the label-restriction list, as defined in
>    [I-D.ietf-teas-yang-te-types], defines a label-start, a label-end, a
>    label-step and a range-bitmap.  The label-start and label-end
>    definitions for OTN should be augmented using the otn-label-start-end
>    grouping.  The label-step definition for OTN should be augmented
>    using the otn-label-step grouping.  It is expected that the otn-
>    label-step will always be equal to its default value (i.e., 1).
> 
>    As described in [RFC7139], in some cases, the TPN assignment rules is
>    flexible (e.g., ODU4 Link) while in other cases the TPN assignment
>    rules are fixed (e.g., ODU1 Link).  In the former case, both TPN and
>    TS ranges are reported, while in the latter case, the TPN range is
>    not reported to indicate that the TPN shall be set equal to the TS
>    number assigned to the ODUk LSP.
> 
>    As described in [RFC7139], in some cases, the TPN assignment rules
>    depends on the TS Granularity (e.g., ODU2 or ODU3 Links).  Different
>    entries in the label-restriction list will report different TPN
>    ranges for each TS granularity supported by the link, as indicated by
>    the tsg attribute in the otn-label-range-info grouping.
> 
>    As described in [RFC7139], in some cases, the TPN ranges are
>    different for different types of ODUk LSPs.  For example, on an ODU2
>    Link with 1,25G TS granularity, there is TPN range 1-4 for ODU1 and
>    another TPN range 1-8 in common for ODU0 and ODUflex.  Different
>    entries in the label-restriction list will report different TPN
>    ranges for different set of ODUk types, as indicated by the odu-type-
>    list in the otn-label-range-info grouping.
> 

@sergiobelotti : what do you think?

**Comment by haomianzheng** [comment]
This issue is confirmed to be complete during IETF 106, and updated into draft-ietf-ccamp-layer1-types-04. 
The issue is now closed.
