### ISSUE TITLE
Signal Aggregation in ietf-trans-client-service

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#46]
Problem Example: STM-1 needs a bandwidth of 155M, while the finest ODUk can provide 1.25G underlay Tunnel (ODU0). The signal can be aggregated to make better use of the tunnnel, therefore when the signal is configured to the tunnel, it can be stated as 'aggregated' or 'non-aggregated'. 

Related Draft: draft-ietf-ccamp-client-signal-yang
Related Module: ietf-trans-client-service / ietf-trans-client-svc-types

Example Proposal to be added in ietf-trans-client-svc-types

  identity work-mode-type {
  }

  identity odu1-aggregate  {
    base work-mode-type;
  }

  identity odu1-not-aggregate  {
    base work-mode-type;
  }

Expected tree shape: 
Current (-01)
        +--rw src-access-ports
        |  +--rw access-node-id?      te-types:te-node-id
        |  +--rw access-ltp-id?       te-types:te-tp-id
        |  +--rw client-signal?       identityref

New 
        +--rw src-access-ports
        |  +--rw access-node-id?      te-types:te-node-id
        |  +--rw access-ltp-id?       te-types:te-tp-id
        |  +--rw client-signal?       identityref
        |  +--rw work-mode?           identityref

**Comment by italobusi** [comment]
Exported to: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/9
