### ISSUE TITLE
Configure Access-point-type to be optical/electrical in ietf-trans-client-service/ietf-eth-tran-service

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#47]
Problem Example:
When configuration the transparent client signals, the corresponding port can be either the optical port or the electrical port on the deivce. It would be useful to specify which type of port to be configured. 

Related Draft: 
  draft-ietf-ccamp-client-signal-yang
Related Module: 
  ietf-trans-client-service / ietf-trans-client-svc-types
  ietf-eth-tran-service / ietf-eth-tran-types 

Proposal to be added in 
  identity access-point-type {
    description "indicates whether it is electronic port or optical point.";
  }

  identity electronic-fe {
    base access-point-type;
  }

  identity electronic-ge {
    base access-point-type;
  }

  identity optical-fe {
    base access-point-type;
  }

  identity optical-ge {
    base access-point-type;
  }

Expected tree shape:
Current (-01)
+--rw src-access-ports
| +--rw access-node-id? te-types:te-node-id
| +--rw access-ltp-id? te-types:te-tp-id
| +--rw client-signal? identityref

New
+--rw src-access-ports
| +--rw access-node-id? te-types:te-node-id
| +--rw access-ltp-id? te-types:te-tp-id
| +--rw client-signal? identityref
| +--rw access-point-type?   identityref

**Comment by italobusi** [comment]
Exported to https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/2
