### ISSUE TITLE
Support of Resource Reservation for operation need

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#48]
Problem: operators need to provide the customer some services for 'trial' which will be temporarily active for some duration. After that the configuration should not be directly removed, as it must be re-open once the customer finish a payment. So a mechanism of resource reservation would be needed for operation. 

Related Draft:
draft-ietf-ccamp-client-signal-yang
Related Module:
ietf-trans-client-service / ietf-trans-client-svc-types
ietf-eth-tran-service / ietf-eth-tran-types

Proposal for adding the following grouping during configuration: 
  grouping resource-reservation-grouping {
    description
      "Use to control the flow of client service";

    container resource-reservation {
      leaf resource-activated-without-reservation {
        type boolean;
      }

      leaf resource-reserved-end-time {
        must "resource-activated-without-reservation == false";
        type yang:date-and-time;
      }
    }
  }

Expected tree shape:
Current (-01)
none. 

New
        +--rw resource-reservation
        |  +--rw resource-activated-without-reservation?        boolean
        |  +--rw resource-reserved-end-time?          yang:date-and-time

**Comment by italobusi** [comment]
Exported to: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/10
