### ISSUE TITLE
[Layer1-types WG LC]Examples needed for layer1-types to indicate the usage of label-range-info

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#49]
Raised during IETF 106 discussion. 

Need to differentiate the usage of label-range-info (more specially tpn-range) and the tpn. Example would be added into layer1-types draft as an appendix.

**Comment by italobusi** [comment]
An initial proposal an example (using JSON language although simplifying some structure to make it easier to read):

[odu-label-restrictions-examples@2019-11-18.txt](https://github.com/haomianzheng/IETF-ACTN-YANG-Model/files/3857615/odu-label-restrictions-examples%402019-11-18.txt)

**Comment by sergiobelotti** [comment]
The example is very useful and clarified the usage of otn-label-range-info grouping. It is needed to add that for each entry of the list label-restriction (form te-types), augmented by augmented by OTN definitons when is needed , you have the range-bitmap indicating which of the TS and TPN range is effectively used .

**Comment by haomianzheng** [comment]
The example has been added into draft-ietf-ccamp-layer1-types-04 as section 4.3. 

This issue is closed.

**Comment by haomianzheng** [comment]
It's worth noting that the text has been enhanced without an example. The example is under re-evaluation to be added in either layer1-types or ietf-otn-topology; probably in an appendix.

**Comment by haomianzheng** [comment]
The example will be described as text, which is expected to appear in the appendix of draft-ietf-ccamp-otn-topo-yang.

**Comment by italobusi** [comment]
Closed in https://tools.ietf.org/html/draft-ietf-ccamp-layer1-types-05
