### ISSUE TITLE
[Layer1-types WG LC] Layer1-types: Standard track and Informational

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#50]
This issue is mentioned in: https://mailarchive.ietf.org/arch/msg/ccamp/yBT8ItiZn73bbskmjCUZpUJiw5c.

The point is the document is standard track for all the types specified in G.709. Besides the authors would prefer some other types from ITU-T G.sup43, as informational.

Following example copied from the YANG model.
identity ODU1 {
base odu-type;
description
"ODU1 protocol (2.49G), RFC7139/ITU-T G.709, as standard track.";
}

identity ODU1e {
base odu-type;
description
"ODU1e protocol (10.35G), RFC7963/ITU-T G.sup43, as informational.";
}

**Comment by haomianzheng** [comment]
BTW, in the draft the reference is also in a dilemma. Usually all the reference in YANG should be normative, while RFC7963 (informational) is not allowed to be normative. 

Seeking for help on the list and from YANG doctors.

**Comment by haomianzheng** [comment]
It is proposed to remove G.sup43 identities in odu-types, after the dicussion with AD and YANG doctor.

**Comment by haomianzheng** [comment]
Regarding the OC-x, our AD is suggesting changing the reference to ANSI. Then the follow changes are proposed to OC-3, OC-12, OC-48, OC-192, OC-768
OLD: 
identity OC-3 {
       base client-signal;
       description
         "Client signal type of OC3";
       reference "Telcordia GR-253-CORE";
     }
NEW:
     identity OC-3 {
       base client-signal;
       description
         "Client signal type of OC3";
       reference 
	     "ANSI T1.105-1995, Synchronous Optical Network (SONET) 
		 Basic Description including Multiplex Structure, Rates, 
		 and Formats";
     }

**Comment by italobusi** [comment]
To be resolved by PR #65

**Comment by italobusi** [comment]
@haomianzheng : please check the changes in https://github.com/haomianzheng/IETF-ACTN-YANG-Model/pull/65/commits/4e9e1e4003ed5ddea17764909a9d50ac648d4ffc
