### ISSUE TITLE
Tag re-naming consideration for ietf-eth-tran-service

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#53]
Now the tag representation in ietf-eth-tran-service is in a relative style, outer-tag, second-tag (as the second from outer)... 
In practice the configuration is more straghtforward to use 'c-vlan' and 's-vlan'... so it is proposed to rename the tag representation to c-vlan and s-vlan. 

For IEEE 802.1 Ethernet, the configuration of the current 'outer-tag' should be c-vlan information; and there is no 'second-tag' configuration;  
For QinQ Ethernet, the configuration of the current 'outer-tag' should be s-vlan, while the 'second-tag' should be c-vlan.

**Comment by italobusi** [comment]
Exported to: https://github.com/ietf-ccamp-wg/draft-ietf-ccamp-client-signal-yang/issues/11
