### ISSUE TITLE
[Layer1-types WG LC]layer1-types: the default value for otn-label-step

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#54]
During the YANG doctor review, we are aware that the default statement won't work under the case choice, so our expected 'setting otn-label-step to 1 by default' does not work in the current model in -04. 

We will remove the 'default 1' statement (as anyway it doesn't work), and seek for alternative solutions.

**Comment by italobusi** [comment]
@haomianzheng : there is some text in section 4.3 about this default value. This text should be reviewed and aligned with with the new solution, once agreed

**Comment by italobusi** [comment]
@italobusi : propose some text changes for the I-D

**Comment by italobusi** [comment]
@haomianzheng : it seems that the default value has not been removed from the label-step attributes

**Comment by italobusi** [comment]
Closed in https://tools.ietf.org/html/draft-ietf-ccamp-layer1-types-05
