### ISSUE TITLE
[Layer1-types WG LC]Label range type and otn-label-type

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#55]
Following up the discussion during YANG doctor review, it seems appropriate to redefine the range-type as an enumeration

Moreover, the (otn-label-type) choice is not unconstrained but constrained by the value of the range-type:

```
                   |     |     |  +--:(otn)
                   |     |     |     +--rw (otn-label-type)?
                   |     |     |        +--:(tributary-port)     // when range-type is tpn
                   |     |     |        |  +--rw tpn?   uint16
                   |     |     |        +--:(tributary-slot)     // when range-type is ts
                   |     |     |           +--rw ts?    uint16

```

**Comment by haomianzheng** [comment]
The otn-label-range-type is converted from identity to enumeration. References have been changed from 'identityref' to normal as well. 

For the constraint on previous (otn-label-type) choice, it should be constrainted by 'range-type' which is assigned in the grouping 'otn-label-range-info'. So the expected shape of tree should be as follow:

    +--:(otn)
       +--rw (range-type)?
          +--:(trib-port)
          |  +--rw otn-tpn?   l1-types:otn-tpn
          +--:(trib-slot)
             +--rw otn-ts?    l1-types:otn-ts
             
A commit to module ietf-layer1-types is available at:
https://github.com/haomianzheng/IETF-ACTN-YANG-Model/commit/18e53c33daf4eebda8ac5af6c8c8cd67e16dc3e2 
and a companion commit to module ietf-otn-topology is done: https://github.com/haomianzheng/IETF-ACTN-YANG-Model/commit/9fcc6a01372669488c434c80c41e65e7c11f95a5

**Comment by haomianzheng** [comment]
TBD after discussion between @italobusi  and @haomianzheng 20200227
1. add the 'when' for case 'trib-slot' and 'trib-port'.
