### ISSUE TITLE
Need for the payload-treatment attribute in OTN Tunnel

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#6]
It seems that the payload-treatment attribute in the OTN tunnel model is not needed

See also TNBI DT discussion: https://github.com/danielkinguk/transport-nbi/pull/29

**Comment by sergiobelotti** [comment]
it seems to me that payload-treatment attribute is more related to a UNI process, and so, I do not see the need to have this type of attribute in OTN tunnel model.

**Comment by haomianzheng** [comment]
Issue Closed: 
payload-treatment has been removed in draft-ietf-ccamp-otn-tunnel-model-03.
