### ISSUE TITLE
Remove src-tpn, src-tsg, src-tributary-slot-count, dst-tpn, dst-tsg and dst-tributary-slot-count from OTN Tunnel

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#7]
The attributes src-tpn, src-tsg, src-tributary-slot-count, dst-tpn, dst-tsg and dst-tributary-slot-count provides information about the labels used by the OTN Tunnel at the ingress/egress points of a domain

This information should be provided in the label hop so it could be removed from the OTN tunnel

See also TNBI DT discussion: https://github.com/danielkinguk/transport-nbi/pull/29

**Comment by italobusi** [comment]
I think these attributes have been defined in the initial version of the model but have now been superseded by the label-hop containers defined in the TE Tunnel and the OTN technology-specific augmentation defined in the latest version of the OTN Tunnel.

**Comment by sergiobelotti** [comment]
I agree on the comment above: label-hop container referred above is related to explicit-route-hop grouping , contained in path-route-object, in which label-hop container is present.

``

**Comment by haomianzheng** [comment]
To make a Decision: 
This issue can be closed after removing src-tpn, src-tsg, src-tributary-slot-count, dst-tpn, dst-tsg and dst-tributary-slot-count in draft-ietf-ccamp-otn-tunnel-model-03.
