### ISSUE TITLE
Discussion on Explicit-route-hop usage in OTN

### ISSUE THREAD

**Issue by haomianzheng** [haomianzheng/IETF-ACTN-YANG-Model#73]
In RFC8776, for the grouping explicit-route-hop has a choice-case structure with 5 options. 
numbered-node-hop/numbered-link-hop/unnumbered-link-hop/as-number/label. 

However these options are mutual exclusive and cannot be used in a combinational way, say unnumbered-link-hop + label. 
This would impact some scenarios where the explicit route need to be described globally through MPI. 

A proposal is to reuse the parameters in explicit-route-hop options in a combinational way when doing augmentation in OTN (tunnel) models. For example, 

```
OLD
       +--:(otn)
          +--ro/rw otn-tpn?   l1-types:otn-tpn
          +--ro/rw tsg?       identityref
          +--ro/rw ts-list?   string
NEW:
       +--:(otn)
          +--ro/rw otn-tpn?   l1-types:otn-tpn
          +--ro/rw tsg?       identityref
          +--ro/rw ts-list?   string		  
	  +--ro/rw node-id?
	  +--ro/rw link-tp-id?
```

**Comment by italobusi** [comment]
This can be achieved by using multiple entries (one for the unnumbered-link-hop and one for the label).

See also:
https://tools.ietf.org/html/draft-ietf-ccamp-transport-nbi-app-statement-11#appendix-B.2

**Comment by haomianzheng** [comment]
Multiple-entry solution solves this problem.
