### ISSUE TITLE
L1-Types: Editorial comments

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#92]
I have reviewed [draft-ietf-ccamp-layer1-types-11](https://datatracker.ietf.org/doc/html/draft-ietf-ccamp-layer1-types) and found few editorial comments:

- [x] Abstract

    ADD
    >    The YANG data model in this document conforms to the Network
    >    Management Datastore Architecture defined in [RFC8342].

    **Resolution**: no action (see comment below)

- [x] Section 1

    OLD
    
    >    This document specifies common data types for use in YANG [RFC7950]
    >    data models of Layer 1 networks.  The derived types and groupings are
    >    types applicable to modeling Traffic Engineering (TE) for Layer 1
    >    networks.
    > 
    >    <...>
    > 
    >    The data model in this draft only defines groupings, typedef and
    >    identities.  There is no configuration or state data as specified in
    >    the Network Management Datastore Architecture [RFC8342].  The
    >    document is consistent with other specifications, including [MEF63]
    >    for Layer 1 service attributes, [ITU-Tg709] and [ITU-Tgsup43] for OTN
    >    data plane definitions.
    
    NEW
    
    >    This document specifies common data types, groupings and identities
    >    for use in YANG [RFC7950]
    >    data models of Layer 1 networks.  The derived types and groupings are
    >    types applicable to modeling Traffic Engineering (TE) for Layer 1
    >    networks.
    > 
    >    <...>
    > 
    >    The document is also consistent with other specifications, including
    >    [MEF63] for Layer 1 service attributes, [ITU-Tg709] and [ITU-Tgsup43]
    >    for OTN data plane definitions.
    > 
    >    The YANG data model in this document conforms to the Network
    >    Management Datastore Architecture defined in [RFC8342].

    **Resolution**: This model just defined types and groupings so no need to comply with [RFC8342]. Update the text as:

    >    This document specifies common data types, groupings and identities
    >    for use in YANG [RFC7950]
    >    data models of Layer 1 networks.  The derived types and groupings are
    >    types applicable to modeling Traffic Engineering (TE) for Layer 1
    >    networks.
    > 
    >    <...>
    > 
    >    The document is also consistent with other specifications, including
    >    [MEF63] for Layer 1 service attributes, [ITU-Tg709] and [ITU-Tgsup43]
    >    for OTN data plane definitions.
    > 
    >    The YANG data model in this document only defines groupings, typedef and
    >    identities and it does not define any configuration or state data, as specified in
    >    the Network Management Datastore Architecture [RFC8342].  

- [x] **Resolution**: move RFC8342 reference as Informational

- [x] Section 3

    OLD
    
    >    In this document, names of data nodes and other data model objects
    >    are prefixed using the standard prefix associated with the
    >    corresponding YANG imported modules.
    > 
    >       +-------------+---------------------------+----------------------+
    >       | Prefix      | YANG module               | Reference            |
    >       +-------------+---------------------------+----------------------+
    >       | l1-types    | ietf-layer1-types         | This Document        |
    >       +-------------+---------------------------+----------------------+
    
    NEW
    
    >    In this document, names of data nodes and other data model objects
    >    are prefixed using the standard prefix associated with the
    >    corresponding YANG imported modules, as shown in Figure 1.
    > 
    >                +==========+===================+===========+
    >                | Prefix   | YANG module       | Reference |
    >                +==========+===================+===========+
    >                | l1-types | ietf-layer1-types | RFC XXXX  |
    >                +----------+-------------------+-----------+
    > 
    >              Table 1: Prefixes and Corresponding YANG Modules
    > 
    >    RFC Editor Note: Please replace XXXX with the number assigned to
    >    the RFC once this draft becomes an RFC.

    **Resolution**: Update the text as:

    >    In this document, names of data nodes and other data model objects
    >    are prefixed using the standard prefix associated with the
    >    corresponding YANG imported modules, as shown in Table 1.
    > 
    >                +==========+===================+===========+
    >                | Prefix   | YANG module       | Reference |
    >                +==========+===================+===========+
    >                | l1-types | ietf-layer1-types | RFC XXXX  |
    >                +----------+-------------------+-----------+
    > 
    >              Table 1: Prefixes and Corresponding YANG Modules
    > 
    >    RFC Editor Note: Please replace XXXX with the number assigned to
    >    the RFC once this draft becomes an RFC.

- [x] Section 4.2

    OLD
    
    >    tributary-slot-granularity:
    > 
    >    This specifies the granularity of the server layer ODU Link (HO ODUk
    >    or ODUCn) supporting a client layer ODU LSP (LO ODUj or ODUk,
    >    respectively).  Three granularities, 1.25G/2.5G/5G, have been
    >    specified.
    
    NEW
    
    >    tributary-slot-granularity:
    > 
    >    This specifies the granularity of the time slots used by the
    >    server layer ODU Link (HO ODUk
    >    or ODUCn) when supporting client layer ODU LSPs (LO ODUj or ODUk,
    >    respectively).  Three granularities, 1.25G/2.5G/5G, have been
    >    specified.

    **Resolution**: agreed

- [x] Section 7

    ADD
    
    >    RFC Editor Note: Please replace XXXX with the number assigned to
    >    the RFC once this draft becomes an RFC.

    **Resolution**: agreed

- [x] #96

- [x] When inserting the odu-label-restrictions-examples.txt file in XML, could you please use the <sourcecode> element and the “name” attribute to enable stripping this file using rfcstrip? See: https://datatracker.ietf.org/doc/html/rfc7991#section-2.48.2. As an example you can also check: https://github.com/ietf-ccamp-wg/transport-nbi/blob/master/I-D%20Applicability%20Statement/draft-ietf-ccamp-transport-nbi-app-statement.xml

**Comment by haomianzheng** [comment]
This open issue is fixed in -13, and can be closed.
