### ISSUE TITLE
Container for OTN label range

### ISSUE THREAD

**Issue by italobusi** [haomianzheng/IETF-ACTN-YANG-Model#98]
It may be useful to group all the attributes used to define the OTN label range within a YANG container:

OLD
```
   +--rw range-type?      otn-label-range-type
   +--rw tsg?             identityref
   +--rw odu-type-list*   identityref
   +--rw priority?        uint8

```

NEW
```
   +--rw otn-label-range
      +--rw range-type?      otn-label-range-type
      +--rw tsg?             identityref
      +--rw odu-type-list*   identityref
      +--rw priority?        uint8

```

**Comment by haomianzheng** [comment]
This one should be accpeted. 
Furthermore, to introduce the OTN container for: 
otn-link-bandwidth, otn-path-bandwidth, 
otn-label-start-end, otn-label-step

**Comment by italobusi** [comment]
Already done:
- grouping otn-path-bandwidth

Done (PR #104 ):
- grouping otn-link-bandwidth
- grouping otn-label-range-info
- grouping otn-label-start-end
- grouping otn-label-step
